
CREATE DATABASE DETRAN;
USE DETRAN; 

CREATE TABLE PROPRIETARIO (
    NOME VARCHAR(100),
    DATA_NASCIMENTO DATE,
    ESTADO VARCHAR(2),
    CIDADE VARCHAR(50),
    BAIRRO VARCHAR(50),
    SEXO CHAR(1),
    IDADE INTEGER,
    CPF VARCHAR(14) PRIMARY KEY,
);

CREATE TABLE VEICULO (
    PLACA VARCHAR(8) PRIMARY KEY,
    CHASSI VARCHAR(20),
    ANO_FABRICACAO INTEGER,
    COR VARCHAR(20),
    FK_MODELO_CODIGO_MODELO INTEGER,
    FK_CATEGORIA_CODIGO_CATEGORIA INTEGER,
    FK_PROPRIETARIO_CPF VARCHAR(14)
);

CREATE TABLE MODELO (
    CODIGO_MODELO INTEGER PRIMARY KEY,
    NOME_MODELO VARCHAR(50)
);

CREATE TABLE CATEGORIA (
    CODIGO_CATEGORIA INTEGER PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(20)
);

CREATE TABLE INFRACAO (
    DATA_HORA DATETIME,
    ID_INFRACAO INTEGER PRIMARY KEY,
    FK_VEICULO_PLACA VARCHAR(8)
);

CREATE TABLE TIPO_INFRACAO (
    IDENTIFICACAO INTEGER PRIMARY KEY,
    VALOR FLOAT,
    FK_INFRACAO_ID_INFRACAO INTEGER
);

CREATE TABLE LOCAL (
    POSICAO_GEOGRAFICA FLOAT PRIMARY KEY,
    VELOCIDADE_PERMITIDA INTEGER,
    FK_INFRACAO_ID_INFRACAO INTEGER
);

CREATE TABLE AGENTE (
    MATRICULA INTEGER PRIMARY KEY,
    NOME VARCHAR(100),
    TEMPO_SERVICO INTEGER,
    FK_INFRACAO_ID_INFRACAO INTEGER
);

CREATE TABLE TELEFONES (
    ID_TELL INTEGER PRIMARY KEY AUTO_INCREMENT,
    NUMERO VARCHAR(15),
    FK_PROPRIETARIO_CPF VARCHAR(14)
);
 

ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_MODELO
    FOREIGN KEY (FK_MODELO_CODIGO_MODELO) REFERENCES MODELO (CODIGO_MODELO);

ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_CATEGORIA
    FOREIGN KEY (FK_CATEGORIA_CODIGO_CATEGORIA) REFERENCES CATEGORIA (CODIGO_CATEGORIA);

ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_PROPRIETARIO
    FOREIGN KEY (FK_PROPRIETARIO_CPF) REFERENCES PROPRIETARIO (CPF)
    ON DELETE CASCADE;


ALTER TABLE TELEFONES ADD CONSTRAINT FK_TELEFONE_PROPRIETARIO
    FOREIGN KEY (FK_PROPRIETARIO_CPF) REFERENCES PROPRIETARIO (CPF)
    ON DELETE CASCADE;


ALTER TABLE INFRACAO ADD CONSTRAINT FK_INFRACAO_VEICULO
    FOREIGN KEY (FK_VEICULO_PLACA) REFERENCES VEICULO (PLACA);


ALTER TABLE TIPO_INFRACAO ADD CONSTRAINT FK_TIPO_INFRACAO_INF
    FOREIGN KEY (FK_INFRACAO_ID_INFRACAO) REFERENCES INFRACAO (ID_INFRACAO);

ALTER TABLE LOCAL ADD CONSTRAINT FK_LOCAL_INF
    FOREIGN KEY (FK_INFRACAO_ID_INFRACAO) REFERENCES INFRACAO (ID_INFRACAO);

ALTER TABLE AGENTE ADD CONSTRAINT FK_AGENTE_INF
    FOREIGN KEY (FK_INFRACAO_ID_INFRACAO) REFERENCES INFRACAO (ID_INFRACAO);